name: nuhoud
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  awesome_snackbar_content: ^0.1.5
  bloc_concurrency: ^0.3.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  date_format: ^2.0.9
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_localization: ^0.3.2
  flutter_localizations:
    sdk: flutter
  flutter_otp_text_field: ^1.5.1+1
  flutter_slider_drawer: ^3.0.2
  flutter_local_notifications: ^19.5.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.17
  flutter_svg_icons: ^0.0.1+4
  get_it: ^8.0.3
  go_router: ^14.8.1
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  phone_form_field: ^10.0.6
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  skeletonizer: ^2.1.0+1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/

  fonts:
    - family: IBMPlex
      fonts:
        - asset: assets/fonts/IBMPlexArabic-Text.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Arabic_R.ttf
